### PR TITLE
Update servers.json

### PR DESCRIPTION
**Pull request by AntoSkate**
I added my server(antoskate.ddns.net to the list)

### CODE REVIEW

**Comment by GreatWizard** [comment]
The server seems down, are you sure about the address?

**Comment by AntoSkate** [comment]
The server is offline cause I have some problems with my connection, I think i'll not host the server in the future too.

**Comment by drizuid** [comment]
@AntoSkate please close your PR if you've changed your mind :)

**Comment by AntoSkate** [comment]
@drizuid ok

**Pull request closed without merging**
